export enum EventsActionType {
  FETCH_EVENTS = 'vasctrac/FETCH_EVENTS',
  FETCH_EVENTS_SUCCESS = 'vasctrac/FETCH_EVENTS_SUCCESS',
  FETCH_EVENTS_FAILURE = 'vasctrac/FETCH_EVENTS_FAILURE',
  CREATE_EVENTS = 'vasctrac/CREATE_EVENTS',
  CREATE_EVENTS_SUCCESS = 'vasctrac/CREATE_EVENTS_SUCCESS',
  CREATE_EVENTS_FAILURE = 'vasctrac/CREATE_EVENTS_FAILURE',
  DELETE_EVENTS = 'vasctrac/DELETE_EVENTS',
  DELETE_EVENTS_SUCCESS = 'vasctrac/DELETE_EVENTS_SUCCESS',
  DELETE_EVENTS_FAILURE = 'vasctrac/DELETE_EVENTS_FAILURE',
}
