export enum LoginActionType {
  LOGIN_USER = 'vasctrac/LOGIN_USER',
  LOGIN_USER_SUCCESS = 'vasctrac/LOGIN_USER_SUCCESS',
  LOGIN_USER_FAILURE = 'vasctrac/LOGIN_USER_FAILURE',
  CHECK_EMAIL = 'vasctrac/LOGIN_CHECK_EMAIL',
  CHECK_EMAIL_SUCCESS = 'vasctrac/LOGIN_CHECK_EMAIL_SUCCESS',
  CHECK_EMAIL_FAILURE = 'vasctrac/LOGIN_CHECK_EMAIL_FAILURE',
  CHECK_PASSWORD = 'vasctrac/LOGIN_CHECK_PASSWORD',
  CHECK_PASSWORD_SUCCESS_TWOFACTOR = 'vasctrac/LOGIN_CHECK_PASSWORD_SUCCESS_TWOFACTOR',
  CHECK_PASSWORD_FAILURE = 'vasctrac/LOGIN_CHECK_PASSWORD_FAILURE',
  CHECK_TWO_FACTOR = 'vasctrac/LOGIN_CHECK_TWO_FACTOR',
  CHECK_TWO_FACTOR_FAILURE = 'vasctrac/LOGIN_CHECK_TWO_FACTOR_FAILURE',
  LOGOUT_USER = 'vasctrac/LOGOUT_USER',
}
