export enum WalktestActionType {
  FETCH_WALKTESTS = 'vasctrac/FETCH_WALKTESTS',
  FETCH_WALKTESTS_SUCCESS = 'vasctrac/FETCH_WALKTESTS_SUCCESS',
  FETCH_WALKTESTS_FAILURE = 'vasctrac/FETCH_WALKTESTS_FAILURE',
}
